version: '3.8'

services:
  wisevision_action_executor:
    build:
      context: .
    container_name: wisevision_action_executor_container
    network_mode: "host"
    ipc: "host"
    pid: "host"
    stdin_open: true
    tty: true
    command: /bin/bash -c "source install/setup.bash && ros2 run wisevision_action_executor automatic_action_service"